project:
  type: website
  output-dir: docs

website:
  title: "Systems Immunology Bootcamp"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "In-Class Materials"
        file: session-materials/sessions.qmd
      - text: "Assignments"
        file: problem-sets/problem-sets.qmd
      - text: "Resources"
        file: resources/resources.qmd

  sidebar:
    - title: "In-Class Materials"
      style: "docked"
      #background: primary
      contents:
        - session-materials/sessions.qmd
        - section: "Session 1"
          contents:
            - session-materials/session1/objects-and-functions.qmd
            - session-materials/session1/vectors-and-conditionals.qmd
            - session-materials/session1/missing-data-and-generators.qmd
            - session-materials/session1/other-data-types.qmd
        - section: "Session 2"
          contents:
            - session-materials/session2/making-functions.qmd
            - session-materials/session2/loops.qmd
            - session-materials/session2/tidyverse-basics.qmd
            - session-materials/session2/split-apply-combine.qmd
            - session-materials/session2/reshaping-and-joining.qmd
        - section: "Session 3"
          contents:
            - session-materials/session3/Intro-data-viz.qmd
            - session-materials/session3/Exercise-1.qmd
            - session-materials/session3/Exercise-2.qmd
        - section: "Session 4"
          contents:
             - session-materials/session4/t-test.qmd
             - session-materials/session4/Intro-models.qmd
             - session-materials/session4/A-simple-model.qmd
             - session-materials/session4/model-building.qmd
             - session-materials/session4/factorial-design.qmd
        
    - title: "Assignments"
      contents:
        - problem-sets/problem-sets.qmd

    - title: "Resources"
      contents:
        - resources/install.qmd
        - resources/resources.qmd
        - resources/quarto-reports.qmd
        - resources/getting-help.qmd
        # navigation items

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    anchor-sections: false
  # pdf: 
  #   prefer-html: false
